### ISSUE TITLE
Some weapons are being distributed regardless of randomization settings.

### ISSUE THREAD

**Issue by battlecarrier** [Nifyr/A-Little-Secret-Ingredient#6]
I've noticed that static inventory weapons distribution is inconsistent as to whether they follows the uniform/empirical/redistribution settings. Things like the candy weapons, the FE:H weapons, some emblem weapons, etc are still being distributed if they are unchecked or set to 0. 

They are also showing up with redistribution which doesn't seem like it should be possible based on my understanding of what redistribution does, as no units are ever equipped with them by default. Could be mistaken there.

Version 1.4.2

**Comment by Nifyr** [comment]
Yeah... It is perhaps not clear, but this is intentional. The option to "force usable weapons" completely ignores your custom distribution. Factoring in your distribution settings would necessitate a different approach to randomization than what the randomizer currently does. It is _possible_ to change, but it is low priority and would require a bunch of work. Not planned.
